app/controllers/orders_controller.rb, app/views/credit_card_status_mailer/guide/status_change_guide_authorized.html.erb, test/controllers/orders_controller_test.rb
Sending a email using webhook to send message to the user and the guide
=> fixing webhook received when a new order is requested by an user

CONTRIBUTING.md
It's need be modified, because the Website use the payment module Stripe and not the Moip.
=> Text Correction

CONTRIBUTING.md
It's a documentation contribution for the issue #7
=> Text Contributing

app/controllers/marketplaces_controller.rb, app/mailers/marketplace_mailer.rb, app/models/marketplace.rb, app/models/payment_type.rb, app/views/layouts/_list_objects_mkt.html.erb, app/views/marketplace_mailer/activate.html.erb, app/views/marketplace_mailer/bank_account.html.erb, app/views/marketplace_mailer/request_app_auth.html.erb, app/views/marketplace_mailer/update.html.erb, app/views/marketplaces/_form.html.erb, app/views/marketplaces/request_external_payment_type_auth.html.erb, config/routes.rb, db/migrate/20170622141524_create_join_table_marketplaces_payment_types.rb, db/migrate/20170622142033_create_payment_types.rb, db/schema.rb, test/controllers/marketplaces_controller_test.rb, test/fixtures/payment_types.yml, test/mailers/marketplace_mailer_test.rb, test/models/marketplace_test.rb, test/models/payment_type_test.rb
The implementation of the authorization with external payment, in this case, the pagseguro payment to be possible make installments payment for users in Brazil
=> Installments payment with pagseguro

app/views/wheres/show.html.erb
Se a tour tiver um guia atrelado a ela, será exibido o card do guia correspondente.
=> Adiciona card do guia à tour

Gemfile.lock, app/assets/javascripts/bootstrap-tagsinput.js, app/assets/javascripts/main.js.erb
Fix #28 
Corrige bug da submissão do formulário quando no tagsinput.
Formulário de criar/editar truppie 
Formulário de criar pacote
=> Fix issue #28

app/assets/javascripts/application.js, app/assets/javascripts/progress_upload.js, app/assets/stylesheets/application.css, app/assets/stylesheets/track_loading.css, app/views/layouts/_track_loading.html.erb, app/views/layouts/application.html.erb, app/views/organizers/_form_guided_tour.html.erb, app/views/organizers/profile_edit.html.erb, app/views/tours/show.html.erb, app/views/welcome/organizer.html.erb, config/locales/en.yml, config/locales/pt-BR.yml
https://github.com/alexanmtz/truppie/issues/34
=> Add upload progress feedback on image based forms

app/assets/javascripts/bootstrap-tagsinput.js, app/assets/javascripts/main.js.erb, app/controllers/tours_controller.rb, app/views/organizers/_form_guided_tour.html.erb
https://github.com/alexanmtz/truppie/issues/48
=> Fix for tags and languages association with tour when creation or editing

app/controllers/tours_controller.rb, app/views/tours/show.html.erb
Olá @alexanmtz 
Esse PR é relacionado à issue #59.
=> Check if user is logged in at show interest button

app/controllers/users/passwords_controller.rb, app/views/devise/passwords/new.html.erb, app/views/devise/shared/_links.html.erb, config/locales/devise.en.yml, config/locales/devise.pt-BR.yml, config/routes.rb
Hi @alexanmtz,
This PR fixes #54
=> Change reset password error message to Truppie's pattern

app/controllers/welcome_controller.rb, app/views/welcome/organizer.html.erb, test/controllers/welcome_controller_test.rb
#63
**welcome_controller.rb**
- Em vez de usar o `where` para buscar o usuário. Mudei para o método `Organizer.find_by(user_id: current_user.id)`. Dessa forma o retorno é o objeto e não se faz mais necessário o uso do any? em <% if `@organizer.any? %>`
- Se o @organizer for encontrado, ele será redirecionado para o profile
- Caso o contrário manterá o comportamento anterior.
**controllers/welcome_controller_test.rb**
- Na classe de test eu criei dois testes, um para quando o guia é um guia e outro quando não(mantem o comportamento anterior)
=> WIP - Redirecionar guia logado para o perfil

.gitignore, Gemfile, Gemfile.lock
Bourbon gem version problem discussed at #71.
public/assets folder should be added to .gitignore file.
=> Bourbon gem version

app/assets/javascripts/mma.js, app/assets/stylesheets/where-template.scss, app/views/layouts/application.html.erb
=> Fix browser console warning/error

app/assets/javascripts/mountain-form.js, app/views/welcome/organizer.html.erb
=> '/welcome/organizer' page not working properly

app/assets/javascripts/places.js.erb, app/views/tours/show.html.erb
=> Maps not loading

ISSUE_TEMPLATE.md, app/assets/javascripts/places.js.erb, app/controllers/users/registrations_controller.rb, app/views/devise/registrations/new.html.erb, app/views/tours/show.html.erb
Adding a hook method before calling the _create_ controller method on _app/controllers/users/registrations_controller.rb_
Also, removing _devise_error_messages_ helper call at _app/views/devise/registrations/new.html.erb_
#79
=> Non standard error message when creating invalid user account

app/assets/stylesheets/mountain-form.scss.erb, app/views/welcome/organizer.html.erb, config/locales/en.yml, config/locales/pt-BR.yml
=> Not indicating required fields when creating an organizer 

Dockerfile, docker-compose-dev.yml, docker-compose-test.yml
=> Refactoring Docker related files

docker-compose-dev-windows.yml
Now we have a specific docker-compose file when running in Windows with Docker Tools.
`docker-compose -f docker-compose-dev-windows.yml up`
#103
=> Project not working in Docker Tools for Windows

app/controllers/application_controller.rb
=> Language preference #105

Gemfile, Gemfile.lock, app/admin/admin_pages.rb, app/admin/admin_users.rb, app/admin/dashboard.rb, app/assets/javascripts/active_admin.js.coffee, app/assets/stylesheets/active_admin.scss, app/assets/stylesheets/application.css, app/controllers/application_controller.rb, app/controllers/welcome_controller.rb, app/models/admin_page.rb, app/models/admin_user.rb, app/views/welcome/faq.html.erb, app/views/welcome/how_it_works.html.erb, app/views/welcome/manifest.html.erb, app/views/welcome/privacy.html.erb, config/initializers/active_admin.rb, config/initializers/active_admin_editor.rb, config/locales/en.yml, config/locales/pt-BR.yml, config/routes.rb, db/migrate/20180327235005_devise_create_admin_users.rb, db/migrate/20180327235010_create_admin_pages.rb, db/schema.rb, db/seeds.rb, features/tour_confirm.feature, test/fixtures/admin_users.yml, test/models/admin_user_test.rb
About the ActiveAdmin PR, I tested and managed to visualize on both the PT and EN pages
=> Admin pages

docker-compose-test-e2e.yml, docker/scripts/run-test-e2e.sh, features/support/env.rb
#109
Command to run the Cucumber Tests: `docker-compose -f docker-compose-test-e2e.yml up`
=> Run Cucumber Tests in a Docker container

README.rdoc
=> Missing docker information at README.rdoc

app/views/guidebooks/show.html.erb
Foi necessário adicionar a function initMap dentro do evento turbolinks:load para que o mapa pudesse ser carregado.
=> Guidebook isn't showing the localization map

app/controllers/guidebooks_controller.rb, app/controllers/tours_controller.rb, app/models/order.rb, app/views/credit_card_status_mailer/_order_table.html.erb, app/views/credit_card_status_mailer/_order_table_guidebook.html.erb, db/migrate/20180731124025_add_package_to_order.rb, db/schema.rb
A new column to reference package on orders to be able to track the orders package info to send to the final user
=> adding package reference to order

app/views/layouts/_order_row.html.erb, app/views/orders/index.html.erb
This PR solves https://github.com/worknenjoy/truppie/issues/130
Please, take a look. Thanks.
=> Show guidebook details on orders page

app/assets/javascripts/main.js.erb, app/assets/stylesheets/fancy-packages.scss, app/assets/stylesheets/welcome.scss, app/controllers/guidebooks_controller.rb, app/controllers/services_controller.rb, app/controllers/tours_controller.rb, app/models/guidebook.rb, app/models/order.rb, app/models/service.rb, app/models/tour.rb, app/views/guidebooks/confirm.html.erb, app/views/organizers/_form_guidebook.html.erb, app/views/organizers/_form_guided_tour.html.erb, app/views/services/_form.html.erb, app/views/services/edit.html.erb, app/views/services/index.html.erb, app/views/services/index.json.jbuilder, app/views/services/new.html.erb, app/views/services/show.html.erb, app/views/services/show.json.jbuilder, app/views/tours/confirm.html.erb, config/locales/en.yml, config/locales/pt-BR.yml, config/routes.rb, db/migrate/20180813131000_add_fields_to_services.rb, db/migrate/20180813142000_create_join_table_tours_services.rb, db/migrate/20180816050000_add_join_table_orders_services.rb, db/migrate/20180816060000_create_references_for_orders.rb, db/migrate/20180816142000_create_join_table_guidebooks_services.rb, db/schema.rb
=> Opções de serviços adicionais para um roteiro

app/controllers/guidebooks_controller.rb, app/controllers/organizers_controller.rb, app/views/credit_card_status_mailer/guide/status_change_guide_refunded.html.erb, app/views/credit_card_status_mailer/guide/status_change_guide_settled.html.erb, app/views/guidebooks/_manage_guidebooks.html.erb, app/views/layouts/_list_objects.html.erb, app/views/layouts/_organizer_dashboard_navbar.html.erb, app/views/layouts/_organizer_dashboard_reservations.html.erb, app/views/marketplace_mailer/activate.html.erb, app/views/marketplace_mailer/bank_account.html.erb, app/views/marketplace_mailer/transfer.html.erb, app/views/marketplace_mailer/update.html.erb, app/views/organizers/manage_guidebooks.html.erb, app/views/organizers/manage_tours.html.erb, app/views/organizers/tos_acceptance_confirm.html.erb, app/views/tours/_manage_tours.erb, app/views/welcome/old_organizer.html.erb, app/views/welcome/organizer.html.erb, config/routes.rb, test/controllers/organizers_controller_test.rb
- Método de manage para tours e guidebooks
- Partials para orders de guidebooks e antigo manage de organizers virou manage_tours
- Teste para nova rota de manage_tours
- Ajuste das rotas para manage_tours e criação de rota manage_guidebooks em routes
- Correção da rota de guidebooks no controller de Guidebook
- Ajuste das rotas de manage para manage_tours em outras páginas que chamavam a rota manage
=> Lista de reservas de tour e guidebooks

Gemfile, Gemfile.lock, app/assets/javascripts/calendar-app.js, app/assets/javascripts/main.js.erb, app/assets/stylesheets/image_gallery.scss, app/controllers/application_controller.rb, app/controllers/tours_controller.rb, app/views/layouts/_product_list.html.erb, app/views/tours/confirm_product.html.erb, app/views/tours/confirm_product_booking.html.erb, app/views/tours/product.html.erb, app/views/tours/products.html.erb, config/initializers/stripe.rb, config/routes.rb, config/secrets.yml, test/controllers/tours_controller_test.rb
a experimental booking system using Reedsy to provide an experience to make reservation in tours and activities. Very raw implmentation to try to make a real test with a real event
=> Marketplace rezdy

config/database.yml, docker-compose-dev.yml
https://github.com/worknenjoy/truppie/issues/140
=> Use bridge network mode to make visiting app in dev easier

README.rdoc
=> Improve README.rdoc
